### ISSUE TITLE
Archive the repo

### ISSUE THREAD

**Issue by elenakrittik** [DisnakeDev/discord-disnake#6]
As per https://github.com/DisnakeDev/guide/pull/49#issue-1416012151:
> it [the shim] is no longer maintained.

And it doesn't look like it will be of much use to revive it at this point.

**Comment by shiftinv** [comment]
I'm going to keep this open (thanks, github) until everything's done, still pending a pypi release eventually

There are also some other related tasks to be finished first in the core project, as well as probably the guide.

**Comment by shiftinv** [comment]
done!
```console
$ docker run --rm -it python:3.10 bash
root@f2abdf3433a9:/# pip install discord-disnake &>/dev/null
root@f2abdf3433a9:/# python
Python 3.10.10 (main, Feb 11 2023, 02:40:33) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import discord
<stdin>:1: UserWarning: The discord-disnake compatibility shim is deprecated and is no longer being updated. Please migrate your project to use https://pypi.org/project/disnake directly.
>>>
```
(thanks, @EQUENOS :pray:)
